/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compressionAlgorithms;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.HashMap;
import org.junit.jupiter.api.Test;

public class HuffmanTest {
    File testFile = new File("src/test/resources/test.txt");
    Huffman hf = new Huffman();

    @Test
    public void testHuffmanCompressWithInCorrectFileExtension() throws IOException {
        assertEquals(false, hf.compress("testFile.csv"));
    }

    @Test
    public void testHuffmanDecompressWithInCorrectFileExtension()
            throws ClassNotFoundException, IOException {
        assertEquals(false, hf.deCompress("testFile.csv"));
    }

    @Test
    public void testCountCharFrequencyInFile()
            throws FileNotFoundException, UnsupportedEncodingException {
        HashMap<Character, Integer> map = hf.countCharFrequencyInFile(testFile);
        assertEquals(Integer.valueOf(69), map.get('e'));
    }

    @Test
    public void testConstructHuffmanTree() throws FileNotFoundException {
        HashMap<Character, Integer> map = hf.countCharFrequencyInFile(testFile);
        Node rootNode = hf.constructHuffmanTree(map);
        assertEquals(Integer.valueOf(738), rootNode.getValue());
    }

    @Test
    public void testConstructBitRepresentations() throws FileNotFoundException {
        HashMap<Character, String> map = hf.constructBitRepresentations(
                hf.constructHuffmanTree(hf.countCharFrequencyInFile(testFile)));
        assertEquals("0110", map.get('a'));
    }

    @Test
    public void testSaveToFile() throws FileNotFoundException {
        File file = new File("src/test/resources/test.txt");
        HashMap<Character, Integer> charFrequencies = hf.countCharFrequencyInFile(file);
        Node rootNode = hf.constructHuffmanTree(charFrequencies);
        HashMap<Character, String> charsBitRepresentations =
                hf.constructBitRepresentations(rootNode);

        hf.saveToFile("src/test/resources/test.txt", "src/test/resources/test",
                charsBitRepresentations);

        File test = new File("src/test/resources/test.huff");
        File map = new File("src/test/resources/test.map");

        assertEquals(true, test.exists());
        assertEquals(true, map.exists());

        test.delete();
        map.delete();
    }

    @Test
    public void testCreateOriginalFile() throws ClassNotFoundException, IOException {
        File file = new File("src/test/resources/test.txt");
        HashMap<Character, Integer> charFrequencies = hf.countCharFrequencyInFile(file);
        Node rootNode = hf.constructHuffmanTree(charFrequencies);
        HashMap<Character, String> charsBitRepresentations =
                hf.constructBitRepresentations(rootNode);

        hf.saveToFile("src/test/resources/test.txt", "src/test/resources/test",
                charsBitRepresentations);

        File test = new File("src/test/resources/test.huff");
        File map = new File("src/test/resources/test.map");

        assertEquals(true, test.exists());
        assertEquals(true, map.exists());

        file.delete();

        Boolean success = hf.deCompress("src/test/resources/test.huff");

        assertEquals(true, success);

        File newFile = new File("test.txt");

        assertEquals(true, newFile.exists());

    }
}
