/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compressionAlgorithms;

import java.io.IOException;
import compressionAlgorithms.algorithms.Huffman;

public class App {

    public static void main(String[] args) throws IOException, ClassNotFoundException {

        if (args.length == 0) {
            System.out.println("no file provided");
        } else {
            String filePath = args[0];
            String fileExtension = filePath.split("\\.")[1];
            Huffman hf = new Huffman();

            if (fileExtension.equals("huff")) {
                hf.deCompress(filePath);

            }
            hf.compress(filePath);
        }
    }
}
